### ISSUE TITLE
Plots are not rendered when building site

### ISSUE THREAD

**Issue by ThomasBeier** [ThomasBeier/GIS_Blog#1]
In my first post, my plots are not being rendered on the output html. Since some of them are 3d-plots this was expected. However, not even the first "normal" raster plot is rendered. The png. file is present in the folder structure tho. It just does not appear on the site

**Comment by gisma** [comment]
did you use the r_ template from the archetypes?

**Comment by ThomasBeier** [comment]
I used the sci-report as stated here: https://gisma-courses.github.io/gi-modules/post/2021-11-16-making-of-academic-websites/

**Comment by gisma** [comment]
i will check asap

**Comment by gisma** [comment]
can you please provide the full error message?

**Comment by ThomasBeier** [comment]
There is no error message, the plots simply do not appear in the r-viewer or when viewing in my browser

**Comment by gisma** [comment]
@ThomasBeier  I am not able to reprduce the issue. could you please provide the preprocessing scripts?

**Comment by ThomasBeier** [comment]
Do you mean the sourced setup script?
it can be found here:
https://github.com/ThomasBeier/src_GIS2021-22

**Comment by gisma** [comment]
@ThomasBeier  sorry for crossposting https://github.com/ThomasBeier/src_GIS2021-22/issues/1#issue-1077852415
